### ISSUE TITLE
npm install is having issue??

### ISSUE THREAD

**Issue by Muneebwasikhan** [bambuser/bambuser-examplebroadcaster-ionic#1]

**Comment by rasapetter** [comment]
Could you provide some more details, please?

**Comment by Muneebwasikhan** [comment]
have done with that now throwing error at 
permission denied, open '/home/muneebkhan/.config/configstore/insight-cordova.json'
im using ubuntu 18.04

**Comment by rasapetter** [comment]
Sorry for your troubles, but these permission issues are most likely unrelated to bambuser-examplebroadcaster-ionic.

I suggest you try looking for solutions with the maintainers of Cordova or Ionic.

**Comment by tomsun** [comment]
@Muneebwasikhan I just updated the `cordova-plugin-bambuser` plugin with a postinstall workflow that is a bit less dependent on system tools. I.e. if step 3 in https://github.com/bambuser/bambuser-examplebroadcaster-ionic/blob/master/README.md#usage was or is an issue, give it a try with the latest version of the plugin, i.e. 0.7.2 or later

In searching around for insight-cordova.json, most people seem to report success if you chown the relevant file to your current user. Not too sure what that file is all about, haven't happened to me.
