### ISSUE TITLE
plugin issue

### ISSUE THREAD

**Issue by chowdarycss** [bambuser/bambuser-examplebroadcaster-ionic#2]
while adding cordova-plugin-bambuser  build is  failing

**Comment by tomsun** [comment]
Hi @chowdarycss , sorry for the late reply. 0.9.5 had a silly mistake like that on the Android side and was the most recent one a bit longer than ideal. (earlier and) later versions should be ok in that regard. As of last week we also have a test suite in place to catch such mishaps more easily.
